usr/bin/llama-bench
usr/bin/llama-cli
usr/bin/llama-completion
usr/bin/llama-quantize
usr/bin/llama-server

# This needs a ton of dependencies through python3-torch. Until we figure out
# how to best deal with it, just ship it in docs
usr/bin/convert_hf_to_gguf.py		usr/share/doc/llama.cpp-tools/scripts/

# Install the themes but rename the simplechat directory
# These are copies of the legacy themes that upstream used to ship until they
# were removed in b8701. We re-add them so that we can ship a DFSG-free
# version.
debian/legacy-themes/public_simplechat/*    usr/share/llama.cpp-tools/llama-server/themes/simplechat
debian/legacy-themes/themes/buttons-top     usr/share/llama.cpp-tools/llama-server/themes/
debian/legacy-themes/themes/wild            usr/share/llama.cpp-tools/llama-server/themes/
